// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// MedicalEquipment is the predicate function for medicalequipment builders.
type MedicalEquipment func(*sql.Selector)

// MedicalType is the predicate function for medicaltype builders.
type MedicalType func(*sql.Selector)

// Physician is the predicate function for physician builders.
type Physician func(*sql.Selector)

// Systemequipment is the predicate function for systemequipment builders.
type Systemequipment func(*sql.Selector)
