// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/poommin2543/app/ent/medicaltype"
	"github.com/poommin2543/app/ent/systemequipment"
)

// MedicaltypeCreate is the builder for creating a Medicaltype entity.
type MedicaltypeCreate struct {
	config
	mutation *MedicaltypeMutation
	hooks    []Hook
}

// SetTypeID sets the Type_ID field.
func (mc *MedicaltypeCreate) SetTypeID(s string) *MedicaltypeCreate {
	mc.mutation.SetTypeID(s)
	return mc
}

// SetTypeName sets the Type_name field.
func (mc *MedicaltypeCreate) SetTypeName(s string) *MedicaltypeCreate {
	mc.mutation.SetTypeName(s)
	return mc
}

// AddMedicalTypeIDs adds the Medical_type edge to Systemequipment by ids.
func (mc *MedicaltypeCreate) AddMedicalTypeIDs(ids ...int) *MedicaltypeCreate {
	mc.mutation.AddMedicalTypeIDs(ids...)
	return mc
}

// AddMedicalType adds the Medical_type edges to Systemequipment.
func (mc *MedicaltypeCreate) AddMedicalType(s ...*Systemequipment) *MedicaltypeCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return mc.AddMedicalTypeIDs(ids...)
}

// Mutation returns the MedicaltypeMutation object of the builder.
func (mc *MedicaltypeCreate) Mutation() *MedicaltypeMutation {
	return mc.mutation
}

// Save creates the Medicaltype in the database.
func (mc *MedicaltypeCreate) Save(ctx context.Context) (*Medicaltype, error) {
	if _, ok := mc.mutation.TypeID(); !ok {
		return nil, &ValidationError{Name: "Type_ID", err: errors.New("ent: missing required field \"Type_ID\"")}
	}
	if _, ok := mc.mutation.TypeName(); !ok {
		return nil, &ValidationError{Name: "Type_name", err: errors.New("ent: missing required field \"Type_name\"")}
	}
	var (
		err  error
		node *Medicaltype
	)
	if len(mc.hooks) == 0 {
		node, err = mc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MedicaltypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mc.mutation = mutation
			node, err = mc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mc.hooks) - 1; i >= 0; i-- {
			mut = mc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MedicaltypeCreate) SaveX(ctx context.Context) *Medicaltype {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mc *MedicaltypeCreate) sqlSave(ctx context.Context) (*Medicaltype, error) {
	m, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	m.ID = int(id)
	return m, nil
}

func (mc *MedicaltypeCreate) createSpec() (*Medicaltype, *sqlgraph.CreateSpec) {
	var (
		m     = &Medicaltype{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: medicaltype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: medicaltype.FieldID,
			},
		}
	)
	if value, ok := mc.mutation.TypeID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: medicaltype.FieldTypeID,
		})
		m.TypeID = value
	}
	if value, ok := mc.mutation.TypeName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: medicaltype.FieldTypeName,
		})
		m.TypeName = value
	}
	if nodes := mc.mutation.MedicalTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicaltype.MedicalTypeTable,
			Columns: []string{medicaltype.MedicalTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: systemequipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return m, _spec
}
