// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/poommin/app/ent/medicaltype"
	"github.com/poommin/app/ent/predicate"
	"github.com/poommin/app/ent/systemequipment"
)

// MedicaltypeUpdate is the builder for updating Medicaltype entities.
type MedicaltypeUpdate struct {
	config
	hooks      []Hook
	mutation   *MedicaltypeMutation
	predicates []predicate.Medicaltype
}

// Where adds a new predicate for the builder.
func (mu *MedicaltypeUpdate) Where(ps ...predicate.Medicaltype) *MedicaltypeUpdate {
	mu.predicates = append(mu.predicates, ps...)
	return mu
}

// SetTypeID sets the Type_ID field.
func (mu *MedicaltypeUpdate) SetTypeID(s string) *MedicaltypeUpdate {
	mu.mutation.SetTypeID(s)
	return mu
}

// SetTypeName sets the Type_name field.
func (mu *MedicaltypeUpdate) SetTypeName(s string) *MedicaltypeUpdate {
	mu.mutation.SetTypeName(s)
	return mu
}

// AddMedicalTypeIDs adds the Medical_type edge to Systemequipment by ids.
func (mu *MedicaltypeUpdate) AddMedicalTypeIDs(ids ...int) *MedicaltypeUpdate {
	mu.mutation.AddMedicalTypeIDs(ids...)
	return mu
}

// AddMedicalType adds the Medical_type edges to Systemequipment.
func (mu *MedicaltypeUpdate) AddMedicalType(s ...*Systemequipment) *MedicaltypeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return mu.AddMedicalTypeIDs(ids...)
}

// Mutation returns the MedicaltypeMutation object of the builder.
func (mu *MedicaltypeUpdate) Mutation() *MedicaltypeMutation {
	return mu.mutation
}

// RemoveMedicalTypeIDs removes the Medical_type edge to Systemequipment by ids.
func (mu *MedicaltypeUpdate) RemoveMedicalTypeIDs(ids ...int) *MedicaltypeUpdate {
	mu.mutation.RemoveMedicalTypeIDs(ids...)
	return mu
}

// RemoveMedicalType removes Medical_type edges to Systemequipment.
func (mu *MedicaltypeUpdate) RemoveMedicalType(s ...*Systemequipment) *MedicaltypeUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return mu.RemoveMedicalTypeIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (mu *MedicaltypeUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(mu.hooks) == 0 {
		affected, err = mu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MedicaltypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mu.mutation = mutation
			affected, err = mu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mu.hooks) - 1; i >= 0; i-- {
			mut = mu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MedicaltypeUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MedicaltypeUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MedicaltypeUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MedicaltypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   medicaltype.Table,
			Columns: medicaltype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: medicaltype.FieldID,
			},
		},
	}
	if ps := mu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.TypeID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: medicaltype.FieldTypeID,
		})
	}
	if value, ok := mu.mutation.TypeName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: medicaltype.FieldTypeName,
		})
	}
	if nodes := mu.mutation.RemovedMedicalTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicaltype.MedicalTypeTable,
			Columns: []string{medicaltype.MedicalTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: systemequipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.MedicalTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicaltype.MedicalTypeTable,
			Columns: []string{medicaltype.MedicalTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: systemequipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{medicaltype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// MedicaltypeUpdateOne is the builder for updating a single Medicaltype entity.
type MedicaltypeUpdateOne struct {
	config
	hooks    []Hook
	mutation *MedicaltypeMutation
}

// SetTypeID sets the Type_ID field.
func (muo *MedicaltypeUpdateOne) SetTypeID(s string) *MedicaltypeUpdateOne {
	muo.mutation.SetTypeID(s)
	return muo
}

// SetTypeName sets the Type_name field.
func (muo *MedicaltypeUpdateOne) SetTypeName(s string) *MedicaltypeUpdateOne {
	muo.mutation.SetTypeName(s)
	return muo
}

// AddMedicalTypeIDs adds the Medical_type edge to Systemequipment by ids.
func (muo *MedicaltypeUpdateOne) AddMedicalTypeIDs(ids ...int) *MedicaltypeUpdateOne {
	muo.mutation.AddMedicalTypeIDs(ids...)
	return muo
}

// AddMedicalType adds the Medical_type edges to Systemequipment.
func (muo *MedicaltypeUpdateOne) AddMedicalType(s ...*Systemequipment) *MedicaltypeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return muo.AddMedicalTypeIDs(ids...)
}

// Mutation returns the MedicaltypeMutation object of the builder.
func (muo *MedicaltypeUpdateOne) Mutation() *MedicaltypeMutation {
	return muo.mutation
}

// RemoveMedicalTypeIDs removes the Medical_type edge to Systemequipment by ids.
func (muo *MedicaltypeUpdateOne) RemoveMedicalTypeIDs(ids ...int) *MedicaltypeUpdateOne {
	muo.mutation.RemoveMedicalTypeIDs(ids...)
	return muo
}

// RemoveMedicalType removes Medical_type edges to Systemequipment.
func (muo *MedicaltypeUpdateOne) RemoveMedicalType(s ...*Systemequipment) *MedicaltypeUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return muo.RemoveMedicalTypeIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (muo *MedicaltypeUpdateOne) Save(ctx context.Context) (*Medicaltype, error) {

	var (
		err  error
		node *Medicaltype
	)
	if len(muo.hooks) == 0 {
		node, err = muo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MedicaltypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			muo.mutation = mutation
			node, err = muo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(muo.hooks) - 1; i >= 0; i-- {
			mut = muo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, muo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MedicaltypeUpdateOne) SaveX(ctx context.Context) *Medicaltype {
	m, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return m
}

// Exec executes the query on the entity.
func (muo *MedicaltypeUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MedicaltypeUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MedicaltypeUpdateOne) sqlSave(ctx context.Context) (m *Medicaltype, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   medicaltype.Table,
			Columns: medicaltype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: medicaltype.FieldID,
			},
		},
	}
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Medicaltype.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := muo.mutation.TypeID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: medicaltype.FieldTypeID,
		})
	}
	if value, ok := muo.mutation.TypeName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: medicaltype.FieldTypeName,
		})
	}
	if nodes := muo.mutation.RemovedMedicalTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicaltype.MedicalTypeTable,
			Columns: []string{medicaltype.MedicalTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: systemequipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.MedicalTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicaltype.MedicalTypeTable,
			Columns: []string{medicaltype.MedicalTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: systemequipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	m = &Medicaltype{config: muo.config}
	_spec.Assign = m.assignValues
	_spec.ScanValues = m.scanValues()
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{medicaltype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return m, nil
}
