// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/poommin2543/app/ent/medicalequipment"
	"github.com/poommin2543/app/ent/predicate"
)

// MedicalEquipmentDelete is the builder for deleting a MedicalEquipment entity.
type MedicalEquipmentDelete struct {
	config
	hooks      []Hook
	mutation   *MedicalEquipmentMutation
	predicates []predicate.MedicalEquipment
}

// Where adds a new predicate to the delete builder.
func (med *MedicalEquipmentDelete) Where(ps ...predicate.MedicalEquipment) *MedicalEquipmentDelete {
	med.predicates = append(med.predicates, ps...)
	return med
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (med *MedicalEquipmentDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(med.hooks) == 0 {
		affected, err = med.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MedicalEquipmentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			med.mutation = mutation
			affected, err = med.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(med.hooks) - 1; i >= 0; i-- {
			mut = med.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, med.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (med *MedicalEquipmentDelete) ExecX(ctx context.Context) int {
	n, err := med.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (med *MedicalEquipmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: medicalequipment.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: medicalequipment.FieldID,
			},
		},
	}
	if ps := med.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, med.driver, _spec)
}

// MedicalEquipmentDeleteOne is the builder for deleting a single MedicalEquipment entity.
type MedicalEquipmentDeleteOne struct {
	med *MedicalEquipmentDelete
}

// Exec executes the deletion query.
func (medo *MedicalEquipmentDeleteOne) Exec(ctx context.Context) error {
	n, err := medo.med.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{medicalequipment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (medo *MedicalEquipmentDeleteOne) ExecX(ctx context.Context) {
	medo.med.ExecX(ctx)
}
