// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/poommin2543/app/ent/medicalequipment"
	"github.com/poommin2543/app/ent/systemequipment"
)

// MedicalEquipmentCreate is the builder for creating a MedicalEquipment entity.
type MedicalEquipmentCreate struct {
	config
	mutation *MedicalEquipmentMutation
	hooks    []Hook
}

// SetName sets the name field.
func (mec *MedicalEquipmentCreate) SetName(s string) *MedicalEquipmentCreate {
	mec.mutation.SetName(s)
	return mec
}

// SetStock sets the stock field.
func (mec *MedicalEquipmentCreate) SetStock(i int) *MedicalEquipmentCreate {
	mec.mutation.SetStock(i)
	return mec
}

// AddSystemequipmentIDs adds the systemequipment edge to Systemequipment by ids.
func (mec *MedicalEquipmentCreate) AddSystemequipmentIDs(ids ...int) *MedicalEquipmentCreate {
	mec.mutation.AddSystemequipmentIDs(ids...)
	return mec
}

// AddSystemequipment adds the systemequipment edges to Systemequipment.
func (mec *MedicalEquipmentCreate) AddSystemequipment(s ...*Systemequipment) *MedicalEquipmentCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return mec.AddSystemequipmentIDs(ids...)
}

// Mutation returns the MedicalEquipmentMutation object of the builder.
func (mec *MedicalEquipmentCreate) Mutation() *MedicalEquipmentMutation {
	return mec.mutation
}

// Save creates the MedicalEquipment in the database.
func (mec *MedicalEquipmentCreate) Save(ctx context.Context) (*MedicalEquipment, error) {
	if _, ok := mec.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if _, ok := mec.mutation.Stock(); !ok {
		return nil, &ValidationError{Name: "stock", err: errors.New("ent: missing required field \"stock\"")}
	}
	var (
		err  error
		node *MedicalEquipment
	)
	if len(mec.hooks) == 0 {
		node, err = mec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MedicalEquipmentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mec.mutation = mutation
			node, err = mec.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mec.hooks) - 1; i >= 0; i-- {
			mut = mec.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mec.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mec *MedicalEquipmentCreate) SaveX(ctx context.Context) *MedicalEquipment {
	v, err := mec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mec *MedicalEquipmentCreate) sqlSave(ctx context.Context) (*MedicalEquipment, error) {
	me, _spec := mec.createSpec()
	if err := sqlgraph.CreateNode(ctx, mec.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	me.ID = int(id)
	return me, nil
}

func (mec *MedicalEquipmentCreate) createSpec() (*MedicalEquipment, *sqlgraph.CreateSpec) {
	var (
		me    = &MedicalEquipment{config: mec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: medicalequipment.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: medicalequipment.FieldID,
			},
		}
	)
	if value, ok := mec.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: medicalequipment.FieldName,
		})
		me.Name = value
	}
	if value, ok := mec.mutation.Stock(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: medicalequipment.FieldStock,
		})
		me.Stock = value
	}
	if nodes := mec.mutation.SystemequipmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   medicalequipment.SystemequipmentTable,
			Columns: []string{medicalequipment.SystemequipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: systemequipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return me, _spec
}
