// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/poommin2543/app/ent/medicaltype"
)

// MedicalType is the model entity for the MedicalType schema.
type MedicalType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MedicalTypeQuery when eager-loading is set.
	Edges MedicalTypeEdges `json:"edges"`
}

// MedicalTypeEdges holds the relations/edges for other nodes in the graph.
type MedicalTypeEdges struct {
	// Systemequipment holds the value of the systemequipment edge.
	Systemequipment []*Systemequipment
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SystemequipmentOrErr returns the Systemequipment value or an error if the edge
// was not loaded in eager-loading.
func (e MedicalTypeEdges) SystemequipmentOrErr() ([]*Systemequipment, error) {
	if e.loadedTypes[0] {
		return e.Systemequipment, nil
	}
	return nil, &NotLoadedError{edge: "systemequipment"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MedicalType) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MedicalType fields.
func (mt *MedicalType) assignValues(values ...interface{}) error {
	if m, n := len(values), len(medicaltype.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	mt.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		mt.Name = value.String
	}
	return nil
}

// QuerySystemequipment queries the systemequipment edge of the MedicalType.
func (mt *MedicalType) QuerySystemequipment() *SystemequipmentQuery {
	return (&MedicalTypeClient{config: mt.config}).QuerySystemequipment(mt)
}

// Update returns a builder for updating this MedicalType.
// Note that, you need to call MedicalType.Unwrap() before calling this method, if this MedicalType
// was returned from a transaction, and the transaction was committed or rolled back.
func (mt *MedicalType) Update() *MedicalTypeUpdateOne {
	return (&MedicalTypeClient{config: mt.config}).UpdateOne(mt)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (mt *MedicalType) Unwrap() *MedicalType {
	tx, ok := mt.config.driver.(*txDriver)
	if !ok {
		panic("ent: MedicalType is not a transactional entity")
	}
	mt.config.driver = tx.drv
	return mt
}

// String implements the fmt.Stringer.
func (mt *MedicalType) String() string {
	var builder strings.Builder
	builder.WriteString("MedicalType(")
	builder.WriteString(fmt.Sprintf("id=%v", mt.ID))
	builder.WriteString(", name=")
	builder.WriteString(mt.Name)
	builder.WriteByte(')')
	return builder.String()
}

// MedicalTypes is a parsable slice of MedicalType.
type MedicalTypes []*MedicalType

func (mt MedicalTypes) config(cfg config) {
	for _i := range mt {
		mt[_i].config = cfg
	}
}
