// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/poommin/app/ent/physician"
	"github.com/poommin/app/ent/predicate"
	"github.com/poommin/app/ent/systemequipment"
)

// PhysicianUpdate is the builder for updating Physician entities.
type PhysicianUpdate struct {
	config
	hooks      []Hook
	mutation   *PhysicianMutation
	predicates []predicate.Physician
}

// Where adds a new predicate for the builder.
func (pu *PhysicianUpdate) Where(ps ...predicate.Physician) *PhysicianUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetPHYSICIANID sets the PHYSICIAN_ID field.
func (pu *PhysicianUpdate) SetPHYSICIANID(s string) *PhysicianUpdate {
	pu.mutation.SetPHYSICIANID(s)
	return pu
}

// SetPHYSICIANNAME sets the PHYSICIAN_NAME field.
func (pu *PhysicianUpdate) SetPHYSICIANNAME(s string) *PhysicianUpdate {
	pu.mutation.SetPHYSICIANNAME(s)
	return pu
}

// SetPHYSICIANEMAIL sets the PHYSICIAN_EMAIL field.
func (pu *PhysicianUpdate) SetPHYSICIANEMAIL(s string) *PhysicianUpdate {
	pu.mutation.SetPHYSICIANEMAIL(s)
	return pu
}

// AddUserPhysicianIDs adds the User_Physician edge to Systemequipment by ids.
func (pu *PhysicianUpdate) AddUserPhysicianIDs(ids ...int) *PhysicianUpdate {
	pu.mutation.AddUserPhysicianIDs(ids...)
	return pu
}

// AddUserPhysician adds the User_Physician edges to Systemequipment.
func (pu *PhysicianUpdate) AddUserPhysician(s ...*Systemequipment) *PhysicianUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pu.AddUserPhysicianIDs(ids...)
}

// Mutation returns the PhysicianMutation object of the builder.
func (pu *PhysicianUpdate) Mutation() *PhysicianMutation {
	return pu.mutation
}

// RemoveUserPhysicianIDs removes the User_Physician edge to Systemequipment by ids.
func (pu *PhysicianUpdate) RemoveUserPhysicianIDs(ids ...int) *PhysicianUpdate {
	pu.mutation.RemoveUserPhysicianIDs(ids...)
	return pu
}

// RemoveUserPhysician removes User_Physician edges to Systemequipment.
func (pu *PhysicianUpdate) RemoveUserPhysician(s ...*Systemequipment) *PhysicianUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pu.RemoveUserPhysicianIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *PhysicianUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PhysicianMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PhysicianUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PhysicianUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PhysicianUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PhysicianUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   physician.Table,
			Columns: physician.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: physician.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.PHYSICIANID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPHYSICIANID,
		})
	}
	if value, ok := pu.mutation.PHYSICIANNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPHYSICIANNAME,
		})
	}
	if value, ok := pu.mutation.PHYSICIANEMAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPHYSICIANEMAIL,
		})
	}
	if nodes := pu.mutation.RemovedUserPhysicianIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.UserPhysicianTable,
			Columns: []string{physician.UserPhysicianColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: systemequipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UserPhysicianIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.UserPhysicianTable,
			Columns: []string{physician.UserPhysicianColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: systemequipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{physician.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// PhysicianUpdateOne is the builder for updating a single Physician entity.
type PhysicianUpdateOne struct {
	config
	hooks    []Hook
	mutation *PhysicianMutation
}

// SetPHYSICIANID sets the PHYSICIAN_ID field.
func (puo *PhysicianUpdateOne) SetPHYSICIANID(s string) *PhysicianUpdateOne {
	puo.mutation.SetPHYSICIANID(s)
	return puo
}

// SetPHYSICIANNAME sets the PHYSICIAN_NAME field.
func (puo *PhysicianUpdateOne) SetPHYSICIANNAME(s string) *PhysicianUpdateOne {
	puo.mutation.SetPHYSICIANNAME(s)
	return puo
}

// SetPHYSICIANEMAIL sets the PHYSICIAN_EMAIL field.
func (puo *PhysicianUpdateOne) SetPHYSICIANEMAIL(s string) *PhysicianUpdateOne {
	puo.mutation.SetPHYSICIANEMAIL(s)
	return puo
}

// AddUserPhysicianIDs adds the User_Physician edge to Systemequipment by ids.
func (puo *PhysicianUpdateOne) AddUserPhysicianIDs(ids ...int) *PhysicianUpdateOne {
	puo.mutation.AddUserPhysicianIDs(ids...)
	return puo
}

// AddUserPhysician adds the User_Physician edges to Systemequipment.
func (puo *PhysicianUpdateOne) AddUserPhysician(s ...*Systemequipment) *PhysicianUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return puo.AddUserPhysicianIDs(ids...)
}

// Mutation returns the PhysicianMutation object of the builder.
func (puo *PhysicianUpdateOne) Mutation() *PhysicianMutation {
	return puo.mutation
}

// RemoveUserPhysicianIDs removes the User_Physician edge to Systemequipment by ids.
func (puo *PhysicianUpdateOne) RemoveUserPhysicianIDs(ids ...int) *PhysicianUpdateOne {
	puo.mutation.RemoveUserPhysicianIDs(ids...)
	return puo
}

// RemoveUserPhysician removes User_Physician edges to Systemequipment.
func (puo *PhysicianUpdateOne) RemoveUserPhysician(s ...*Systemequipment) *PhysicianUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return puo.RemoveUserPhysicianIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (puo *PhysicianUpdateOne) Save(ctx context.Context) (*Physician, error) {

	var (
		err  error
		node *Physician
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PhysicianMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PhysicianUpdateOne) SaveX(ctx context.Context) *Physician {
	ph, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return ph
}

// Exec executes the query on the entity.
func (puo *PhysicianUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PhysicianUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PhysicianUpdateOne) sqlSave(ctx context.Context) (ph *Physician, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   physician.Table,
			Columns: physician.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: physician.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Physician.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.PHYSICIANID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPHYSICIANID,
		})
	}
	if value, ok := puo.mutation.PHYSICIANNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPHYSICIANNAME,
		})
	}
	if value, ok := puo.mutation.PHYSICIANEMAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: physician.FieldPHYSICIANEMAIL,
		})
	}
	if nodes := puo.mutation.RemovedUserPhysicianIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.UserPhysicianTable,
			Columns: []string{physician.UserPhysicianColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: systemequipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UserPhysicianIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   physician.UserPhysicianTable,
			Columns: []string{physician.UserPhysicianColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: systemequipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	ph = &Physician{config: puo.config}
	_spec.Assign = ph.assignValues
	_spec.ScanValues = ph.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{physician.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return ph, nil
}
