// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/poommin2543/app/ent/physician"
	"github.com/poommin2543/app/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	physicianFields := schema.Physician{}.Fields()
	_ = physicianFields
	// physicianDescName is the schema descriptor for name field.
	physicianDescName := physicianFields[0].Descriptor()
	// physician.NameValidator is a validator for the "name" field. It is called by the builders before save.
	physician.NameValidator = physicianDescName.Validators[0].(func(string) error)
	// physicianDescEmail is the schema descriptor for email field.
	physicianDescEmail := physicianFields[1].Descriptor()
	// physician.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	physician.EmailValidator = physicianDescEmail.Validators[0].(func(string) error)
}
