// Code generated by entc, DO NOT EDIT.

package systemequipment

const (
	// Label holds the string label denoting the systemequipment type in the database.
	Label = "systemequipment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSystemID holds the string denoting the system_id field in the database.
	FieldSystemID = "system_id"
	// FieldMedicalID holds the string denoting the medical_id field in the database.
	FieldMedicalID = "medical_id"
	// FieldTypeID holds the string denoting the type_id field in the database.
	FieldTypeID = "type_id"
	// FieldPHYSICIANID holds the string denoting the physician_id field in the database.
	FieldPHYSICIANID = "physician_id"
	// FieldSystemDATA holds the string denoting the system_data field in the database.
	FieldSystemDATA = "system_data"

	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeOwnera holds the string denoting the ownera edge name in mutations.
	EdgeOwnera = "ownera"
	// EdgeOwnerf holds the string denoting the ownerf edge name in mutations.
	EdgeOwnerf = "ownerf"

	// Table holds the table name of the systemequipment in the database.
	Table = "systemequipments"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "systemequipments"
	// OwnerInverseTable is the table name for the Physician entity.
	// It exists in this package in order to avoid circular dependency with the "physician" package.
	OwnerInverseTable = "physicians"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "physician_user_physician"
	// OwneraTable is the table the holds the ownera relation/edge.
	OwneraTable = "systemequipments"
	// OwneraInverseTable is the table name for the Medicalequipment entity.
	// It exists in this package in order to avoid circular dependency with the "medicalequipment" package.
	OwneraInverseTable = "medicalequipments"
	// OwneraColumn is the table column denoting the ownera relation/edge.
	OwneraColumn = "medicalequipment_medical_equipment"
	// OwnerfTable is the table the holds the ownerf relation/edge.
	OwnerfTable = "systemequipments"
	// OwnerfInverseTable is the table name for the Medicaltype entity.
	// It exists in this package in order to avoid circular dependency with the "medicaltype" package.
	OwnerfInverseTable = "medicaltypes"
	// OwnerfColumn is the table column denoting the ownerf relation/edge.
	OwnerfColumn = "medicaltype_medical_type"
)

// Columns holds all SQL columns for systemequipment fields.
var Columns = []string{
	FieldID,
	FieldSystemID,
	FieldMedicalID,
	FieldTypeID,
	FieldPHYSICIANID,
	FieldSystemDATA,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Systemequipment type.
var ForeignKeys = []string{
	"medicalequipment_medical_equipment",
	"medicaltype_medical_type",
	"physician_user_physician",
}

var (
	// SystemIDValidator is a validator for the "System_ID" field. It is called by the builders before save.
	SystemIDValidator func(string) error
)
