// Code generated by entc, DO NOT EDIT.

package physician

const (
	// Label holds the string label denoting the physician type in the database.
	Label = "physician"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPHYSICIANID holds the string denoting the physician_id field in the database.
	FieldPHYSICIANID = "physician_id"
	// FieldPHYSICIANNAME holds the string denoting the physician_name field in the database.
	FieldPHYSICIANNAME = "physician_name"
	// FieldPHYSICIANEMAIL holds the string denoting the physician_email field in the database.
	FieldPHYSICIANEMAIL = "physician_email"

	// EdgeUserPhysician holds the string denoting the user_physician edge name in mutations.
	EdgeUserPhysician = "User_Physician"

	// Table holds the table name of the physician in the database.
	Table = "physicians"
	// UserPhysicianTable is the table the holds the User_Physician relation/edge.
	UserPhysicianTable = "systemequipments"
	// UserPhysicianInverseTable is the table name for the Systemequipment entity.
	// It exists in this package in order to avoid circular dependency with the "systemequipment" package.
	UserPhysicianInverseTable = "systemequipments"
	// UserPhysicianColumn is the table column denoting the User_Physician relation/edge.
	UserPhysicianColumn = "physician_user_physician"
)

// Columns holds all SQL columns for physician fields.
var Columns = []string{
	FieldID,
	FieldPHYSICIANID,
	FieldPHYSICIANNAME,
	FieldPHYSICIANEMAIL,
}
